### ISSUE TITLE
Button interference when selecting image

### ISSUE THREAD

**Issue by remkus** [hlashbrooke/Instant-Featured-Image#1]
When I go the the library and select an image the button is displaying some interference
![](http://i.remk.us//38/z78vk1ee2o4k8.png)

**Comment by hlashbrooke** [comment]
I don't get that on my side - I reckon it's due to your 'insert' button being longer because of the localisation. Should be simple enough to sort out with a CSS fix.

**Comment by remkus** [comment]
Actually, the string is not translated in the example. When selecting an image out of the existing library is when I get that btw
