### ISSUE TITLE
Possibly reuse available translations

### ISSUE THREAD

**Issue by remkus** [hlashbrooke/Instant-Featured-Image#2]
Perhaps it's possible to reuse the available translations for the insert text and the Set as featured image text?

**Comment by hlashbrooke** [comment]
I'll look into this - the only issue I could see would be including the '&' or 'and' - not sure if there's an already localised string for that in core, but will see what I can find.

**Comment by remkus** [comment]
Not sure, but I guess the ampersand would work in most cases

**Comment by hlashbrooke** [comment]
I changed the text slightly, but I couldn't reuse existing strings. The 'set featured image' part would have been fine, but I couldn't find a standalone 'insert' string or anything else that would really work for the rest.
